-- begin STOCKS_CURRENCY
create unique index IDX_STOCKS_CURRENCY_UNIQ_CODE on STOCKS_CURRENCY (CODE) ^
-- end STOCKS_CURRENCY
-- begin STOCKS_OPERATION
alter table STOCKS_OPERATION add constraint FK_STOCKS_OPERATION_STOCK foreign key (STOCK_ID) references STOCKS_STOCK(ID)^
-- end STOCKS_OPERATION
-- begin STOCKS_STOCK
alter table STOCKS_STOCK add constraint FK_STOCKS_STOCK_CURRENCY foreign key (CURRENCY_ID) references STOCKS_CURRENCY(ID)^
create unique index IDX_STOCKS_STOCK_UNIQ_CODE on STOCKS_STOCK (CODE) ^
create unique index IDX_STOCKS_STOCK_UNIQ_NAME on STOCKS_STOCK (NAME) ^
-- end STOCKS_STOCK
